name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  package:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Récupération des fichiers du git
    
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      uses: docker/login-action@v2.1.0
      with:
        username: ymtkudasai
        password: ${{secrets.DOCKERHUB_PASSWORD}}
